### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Edfgdz** [ohmae/touch-icon-extractor#2]
1.Let this app remember Transparent grid option enabled or disabled status. 

For example when user close this option then when user use this app next time this option will be disabled automatically. 

![Screenshot_2021-11-17-19-57-36-395_net mm2d webclip](https://user-images.githubusercontent.com/26460124/142196740-fe00159c-9eba-4526-8e90-b130d2ba9fa0.jpg)

2.Add Download button next to each results to let user could Download those favicon results directly.

**Comment by ohmae** [comment]
Thanks. But that opinion is about the sample app, The app is just for checking this library.
https://github.com/ohmae/touch-icon-extractor-sample

**Comment by Edfgdz** [comment]
I think these two suggestions won't make this app complex.

And it says its intention is to extract Webclip icon information.

![Screenshot_2021-11-18-08-32-08-134_com xbrowser play](https://user-images.githubusercontent.com/26460124/142318007-65e32b8e-1811-4817-9440-c8576c5a860c.jpg)
